!recipe
ingredients:
  rice: 1.5 cups
  sesame oil: 4 tsp
  tofu: 1 lbs
  garlic: 2
  green onion: 2
  bean sprout: 4 oz
  carrot: 2
  zucchini: 1
  egg: 2
  gochujang: 0.25 cups
steps:
  - heat pan on medium
  - start rice
  - chop vegtables
  - pan fry bean sprout, zucchini, carrot, green onion, with sesame oil
  - salt lightly when nearly done frying
  - soft boil 2 eggs
  - make sauce, gochujang, 2 tsp sesame oil, 2 tbs water
  - cube tofu
  - optionally, serve with kimchi
