!recipe
ingredients:
  rice: 1.5 cups
  red onion: 1
  serrano pepper: 2
  garlic: 3
  star anise: 1
  cinnamon: 2 tsp
  coconut milk: 400 ml
  ground tumeric: 1 tbs
  vegetable broth: 400 ml
  canned chickpea: 880 g
  spinach: 10 oz
  lime juice: 1 tbs
  salt: 0.5 tsp
steps:
  - start rice
  - garlic, serrano and onion
  - start pan on medium low with olive oil
  - cook garlic, serrano, and star anise for a few minutes, until garlic lightly brown
  - add cinnamon for 30 seconds
  - add red onions, and turn up to medium high
  - cook until onions soft 5-10 min
  - add coconut milk, tumeric, and chickpeas
  - boil and then 10min simmer
  - add spinach, lime juice, and salt
