!recipe
ingredients:
  rice: 1.5 cups
  tofu: 1 lbs
  sesame oil: 4 tsp
  soy sauce: 2 tbs
  chili garlic sauce: 3 tsp
  vegetable broth: 0.25 cup
  garlic: 3
  brown sugar: 3 tsp
  green onion: 2
  eggplant: 2
  rice vinegar: 2 tbs
steps:
  - pre heat oven 400F
  - heat tofu pan on medium
  - start rice
  - pan fry tofu for 7 min on each side
  - thinly slice eggplant, lay flat, drizzle with olive oil
  - bake eggplant 15 min, rotate pan, 15 min
  - chop garlic and green onion
  - make sauce, brown sugar, soy sauce, rice vinegar, chili, vegetable broth
  - saute green onions and garlic on medium for 1 min with sesame oil
  - add baked eggplant and sauce to pan
  - saute until sauce thickens 1-3 min
  - add tofu and mix in with sauce
