!recipe
ingredients:
  rice: 2 cups
  vegtable oil: 1 tbs
  yellow onion: 2
  russet potato: 2
  carrot: 2
  gardein beef crumble: 390 g
  golden curry block: 110 g
steps:
  - start rice
  - heat oil in pot on medium low
  - cut onion, carrot, and potato
  - cook vegtables on medium heat for 5min
  - add 800ml water, bring to boil
  - cover and simmer for 10min
  - add gardein beef crumble
  - cover and simmer for 5min
  - curry block, while simmering for 5min
