!recipe
ingredients:
  ginger: 2 tbs
  garlic: 2
  baby bok choy: 1
  shallot: 1
  lime juice: 2 tbs
  serrano pepper: 1
  sugar: 1 tsp
  coconut milk: 0.75 cups
  red curry paste: 36 g
  soy sauce: 1 tbs
  rice noodle: 0.5 lbs
  tempeh: 0.5 lbs
  crispy onion: 2 tbs
  vegtable oil: 3 tbs
  salt: 1 tsp
  pepper: 1 tsp
steps:
  - boil large pot of water for rice noodles
  - thinly slice shallot, garlic, and baby bok choy, grate ginger
  - pickle shallot; add to 1 tbs lime juice, 1 tsp sugar, and a pinch of salt
  - when water boils add rice noodles and soak off heat for 8 min then replace with cold water
  - broth
    - saute for 2 min on medium heat, 1 tbs oil with ginger, garlic, and red curry paste
    - add 1.5 cups water, soy sauce, 3/4 cup coconut milk, half tsp salt, and a pinch of pepper
    - bring to simmer and add baby bok choy
  - heat pan on medium
  - crumble tempeh, pan fry for 12 min with 1 tbs oil, pinch of salt and pepper (just below medium, 7 o-clock)
  - server with noodle, broth, shallot, tempeh, crispy onions, and sliced serranos
