!recipe
ingredients:
  tofu: 1lbs
  rice: 1 cup
  vegtable oil: 2 tsp
  brown mushroom: 8 oz
  red onion: 1
  garlic: 3
  broccolini: 1
  snap peas: 1 cup
  teriyaki sauce: 120g
  sunflower seeds: 1.5 tbs
  lime juice: 1 tsp
  salt: 0.25 tsp

steps:
  - start tofu pan
  - start rice
  - chop vegtables
  - fry tofu for 7 min on medium
  - saute 1 tsp oil, red onion, mushroom, with 0.25 tsp salt on medium high for 6min
  - add garlic, chopped vegtables and sunflower seeds, medium with lid for 4min
  - add teriyaki sauce mix, lime juice, and tofu, heat for ~30sec until comes together
