!recipe
ingredients:
  white onion: 1
  garlic: 4
  rosemary: 2 tsp
  thyme: 2 tsp
  ap flour: 0.5 cup
  salt: 2 tsp
  pepper: 1 tsp
  tomato paste: 5 oz
  vegetable broth: 4 cup
  whole wheat pasta: 12 oz
  kale: 6 oz
  italian sausage: 4
  sugar: 1 tbsp
  light coconut milk: 1
steps:
  - add italian sausages to pot
  - chop onion, garlic
  - measure rosemary, thyme, flour; 5 cups water
  - wash and chop kale into small pieces
  - after italian sausages are cooked, take them out 
  - saute onion, garlic in pot for 5 min
  - add rosemary, thyme, flour. stir well and cook 1 min
  - add salt, pepper, tomato paste. stir well
  - add broth gradually, stirring out lumps
  - add 5 cups water and bring to simmer
  - slice up the cooked sausages
  - add pasta, kale, sugar, coconut milk
  - cook 10 minutes
  - add sausages
