!recipe
ingredients:
  tofu: 1.5 lbs
  red cabbage: 0.5
  carrot: 2
  cucumber: 1.5
  radish: 8
  red bell pepper: 1
  green onion: 8
  cilantro: 1 cup
  peanut: 0.5 cup
  garlic: 2
  ginger: 2 tbs
  soy sauce: 4 tbs
  rice vinegar: 8 tbs
  peanut butter: 160g
  sesame oil: 2 tsp
  chili garlic sauce: 2 tsp
  lime juice: 2 tsp
steps:
  - https://itdoesnttastelikechicken.com/peanut-thai-salad-with-grilled-tofu/
  - heat tofu pan on medium
  - pan fry tofu for about 7 min on each side
  - slice vegtables
  - mix dressing, remember 4 tsb water
