!recipe
ingredients:
  rice: 1.5 cups
  tofu: 1 lbs
  sesame oil: 4 tsp
  soy sauce: 3 tbs
  chili garlic sauce: 2 tsp
  peanut butter: 30 g
  honey: 1 tbs
  lime juice: 1 tbs
  shittake mushroom: 8 oz
  red bell pepper: 1
  broccoli: 1
  garlic: 2
  green onion: 3
  ginger: 1 tbs
steps:
  - https://minimalistbaker.com/20-minute-tofu-stir-fry/
