!recipe
rating: 0..3 # OPTIONAL: 0: not again, 1: okay, 2: good, 3: great
ingredients: # Must be defined in `$GAMP_CONFIG_DIR/ingredients.yaml`
  spaghetti: 14 oz
  peanut butter: 170g
  soy sauce: 4 tbs
  rice vinegar: 4 tbs
  honey: 2 tbs
  sesame oil: 2 tbs
  tofu: 16 oz
  vegtable oil: 2 tbs
  garlic: 6
  ginger: 4 tsp
  green onion: 8
  red cabbage: 4 cups
  peanut: 1/3 cup
steps:
  - chop onion
