!recipe
ingredients:
  tofu: 1 lbs
  soy sauce: 7 tbs
  red cabbage: 0.5
  carrot: 2
  cucumber: 1.5
  radish: 8
  red bell pepper: 1
  green onion: 8
  cilantro: 1 cup
  peanut: 0.5 cup
  garlic: 2
  ginger: 2 tbs
  rice vinegar: 0.5 cup
  peanut butter: 0.5 cup
  sesame oil: 2 tsp
  chili garlic sauce: 2 tsp
  lime juice: 1 tbs
steps:
  - https://itdoesnttastelikechicken.com/peanut-thai-salad-with-grilled-tofu/
