!recipe
ingredients:
  broccoli: 1
  red bell pepper: 1
  brown mushroom: 8 oz
  whole wheat pasta: 1 lbs
  red onion: 1
  olive oil: 2 tbs
  butternut squash: 8 oz
  salt: 0.5 tsp
  pepper: 0.5 tsp
  pesto: 6 oz
  crushed red pepper: 1 tbs
  italian sausage: 4
steps:
  - preheat oven to 400F
  - chop vegtables
  - place on parchement paper in a backing sheet
  - toss with olive oil salt and pepper
  - roast for 25-30, toss in the middle
  - cook sausages
  - make al dente pasta, and drain, reserving some water
  - mix pasta, pesto, sausages, roasted vegtables, and about 1/4 cup pasta water
  - season with salt, pepper, and crushed red pepper
