!recipe
ingredients:
  yellow onion: 1 cup
  tempeh: 0.5 lbs
  oregano: 1 tsp
  ground cumin: 1 tsp
  paprika: 1 tsp
  cayenne pepper: 0.25 tsp
  olive oil: 1 tbs
  cheese: 2
  garlic: 4
  shallot: 1
  poblano pepper: 2
  avocado: 2
  roma tomato: 3
  salt: 1 tsp
  pepper: 1 tsp
  lime juice: tsp
  tortilla: 5

steps:
  - roast poblano peppers for x min under broiler, and wrap in foil
  - chop onion and garlic
  - saute tempeh in olive oil until light brown, 5 min on medium
  - add onions, 3 garlic cloves, and spices 2-3 min
  - peal roasted poblanos and add to pan
  - dice shallot and tomatoes
  - make guac by mixing 2 avocados, 1 garlic clove, shallot, tomato, salt, pepper, and lime juice
  - make into burrito or quesadillas
