!recipe
ingredients:
  vegtable oil: 3 tbs
  tofu: 1.5 lbs
  rice noodle: 12 oz
  serrano pepper: 3
  garlic: 3
  carrot: 2
  bean sprout: 4 oz
  green onion: 5
  tamrind concentrate: 2 tsp
  soy sauce: 9 tbs
  sugar: 0.25 cup
  chili garlic sauce: 2 tbs
  lime juice: 2 tbs
  vegan fish sauce: 2 tbs
  sesame oil: 1 tsp
  peanut: 0.75 cups
steps:
  - heat tofu pan on medium
  - dice garlic and pepper
  - chop carrots, green onion, and peanuts
  - drain, press, slice tofu
  - fry tofu for about 7min on each side
  - bring a large pot of water to a boil
  - when tofu have 5 min left, start rice noodles
  - heat sesame oil on medium low in wok
  - when noodles have 3 min left, saute tofu, garlic, and diced chili in wok
  - make sauce by mixing tamrind, 0.5 cup soy sauce, sugar, chili garlic sauce,  lime juice, and vegan fish sauce
  - microwave sauce for 30 seconds?
  - when noodles are done, mix everything together in pot noodles, sauce, carrots, green onion, bean sprouts, and peanuts
  - cook until sauce thickens, 20-40 seconds on medium
