!recipe
ingredients:
  white mushroom: 5oz
  lime juice: 2 tbs
  green onion: 2
  serrano pepper: 2
  carrot: 2
  rice: 1.5 cups
  coconut milk: 800ml
  tofu: 1lbs
  red bell pepper: 1
  ginger: 1 tbs
  bay leaf: 1
  vegetable broth: 4 cup
  brown sugar: 1 tsp
  salt: 0.5 tsp

steps:
  - https://www.cookwithmanali.com/vegan-tom-kha-gai-thai-coconut-soup/
  - start rice
  - grate ginger
  - simmer vegtable broth, coconut milk, ginger, and bay leaf for 5 min
  - chop tofu, mushroom, green onion, red bell pepper, carrots, and serrano
  - add tofu and vegtables
  - simmer for 10min
  - add salt, sugar, and lime juice
