!recipe
ingredients:
  white mushroom: 5oz
  lime juice: 2 tbs
  green onion: 2
  serrano pepper: 2
  carrot: 2
  rice: 1.5 cups
  coconut milk: 600ml
  tofu: 1lbs
  red bell pepper: 1
  ginger: 1 tbs
  bay leaf: 1
  vegetable broth: 2 cup
  brown sugar: 1 tsp

steps:
  - make soup
